# Generated by Django 5.2.8 on 2025-11-15 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='company',
        ),
        migrations.RemoveField(
            model_name='application',
            name='max_salary',
        ),
        migrations.RemoveField(
            model_name='application',
            name='min_salary',
        ),
        migrations.RemoveField(
            model_name='application',
            name='position_description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='position_title',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=255)),
                ('position_description', models.TextField()),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companyprofile')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jobposting'),
        ),
    ]
